#!/usr/bin/env bash
# gen-directions-index.sh — generate the "Directions Index" table from each doc's TRIGGERS header.
#
# The Index maps topic → master doc so a running project reads the *current* doc on demand
# (see the "Directions Index" section in the tool's global instructions). Generating it from the docs'
# own TRIGGERS: headers means the table can never drift from the docs.
#
# Usage:
#   gen-directions-index.sh                      # print the full section to stdout (preview)
#   gen-directions-index.sh --base '[LOCAL_DIRECTIONS_PATH]'   # use a placeholder base path
#   gen-directions-index.sh --write FILE         # splice the body between the markers in FILE
#   gen-directions-index.sh --write FILE --base '[LOCAL_DIRECTIONS_PATH]'
#
# --write requires FILE to already contain the two marker lines:
#   <!-- DIRECTIONS-INDEX:START ... -->
#   <!-- DIRECTIONS-INDEX:END -->
# Everything between them is replaced; the markers themselves are kept. If absent, exits 2.
#
# Each row's "When the task involves…" cell = the first few TRIGGERS keywords (falls back to the
# doc's H1 title when a doc has no TRIGGERS line). Tune MAX_KW below.
#
# Exit codes: 0 ok · 2 error (no docs found / markers missing).

set -eo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BASE="$REPO"
MAX_KW=6
WRITE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --base)  BASE="$2"; shift 2 ;;
    --write) WRITE="$2"; shift 2 ;;
    -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
    *) echo "gen-directions-index.sh: unknown arg '$1'" >&2; exit 2 ;;
  esac
done

# --- extract a one-line description for a doc -------------------------------------------------
describe() {
  local f="$1" raw kw title out t n i
  # First TRIGGERS-style header line, in any of: "TRIGGERS:", "**Triggers:**", "> Triggers:"
  raw=$(grep -iE -m1 '^[>* ]*triggers?[:* ]' "$f" 2>/dev/null || true)
  if [ -n "$raw" ]; then
    kw=${raw#*:}                                   # drop label up to first colon
    kw=$(printf '%s' "$kw" | sed -E 's/^[* ]+//; s/[* ]+$//')
    local IFS=','
    # shellcheck disable=SC2206
    local arr=($kw)
    n=${#arr[@]}
    out=""
    for ((i=0; i<n && i<MAX_KW; i++)); do
      t=$(printf '%s' "${arr[i]}" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')
      [ -z "$t" ] && continue
      out="$out${out:+, }$t"
    done
    [ "$n" -gt "$MAX_KW" ] && out="$out …"
    printf '%s' "$out"
  else
    title=$(grep -m1 '^# ' "$f" | sed -E 's/^#+[[:space:]]*//')
    printf '%s' "$title"
  fi
}

# --- build the body (intro + table + why) ----------------------------------------------------
build_body() {
  local f desc count=0
  printf 'The Directions guidance docs are the **single source of truth** in the master repo. Do **not**\n'
  printf 'rely on a copy inside the current project — copies drift and never receive new house-style. When a\n'
  printf 'task matches a trigger below, **read the master doc on demand** from `%s/`:\n\n' "$BASE"
  printf '| When the task involves… | Read |\n'
  printf '|---|---|\n'
  for f in "$REPO"/[0-9][0-9]_*.md; do
    [ -e "$f" ] || continue
    # Skip redirect stubs (consolidated docs that just point elsewhere) — their triggers live on
    # the canonical doc, so they shouldn't be double-listed.
    grep -qiE '^[[:space:]]*LOAD:[[:space:]]*redirect' "$f" && continue
    desc=$(describe "$f")
    desc=${desc//|/\/}                              # never let a pipe break the table
    printf '| %s | `%s` |\n' "$desc" "$(basename "$f")"
    count=$((count+1))
  done
  if [ "$count" -eq 0 ]; then
    echo "gen-directions-index.sh: no numbered docs found in $REPO" >&2
    exit 2
  fi
  printf '\n**Why read-on-demand:** Universal docs used to be copied into each project at `/setup`, so updates\n'
  printf 'never reached already-set-up projects (N copies silently drift). This Index lets a running project —\n'
  printf 'which reads global + project instructions — pull the *current* master doc instead.\n'
}

BODY=$(build_body)

if [ -z "$WRITE" ]; then
  # preview: full section
  printf '## Directions Index (Read-on-Demand, Not Copied)\n\n'
  printf '<!-- DIRECTIONS-INDEX:START — generated by scripts/gen-directions-index.sh; do not edit by hand -->\n'
  printf '%s\n' "$BODY"
  printf '<!-- DIRECTIONS-INDEX:END -->\n'
  exit 0
fi

# --write: splice BODY between the markers in $WRITE
[ -f "$WRITE" ] || { echo "gen-directions-index.sh: no such file: $WRITE" >&2; exit 2; }

# Auto-bootstrap: if there are no markers yet but a "## Directions Index" heading exists, replace
# that section's body (heading → next '---' or next '## ') with empty markers, so first run works.
if ! grep -q 'DIRECTIONS-INDEX:START' "$WRITE"; then
  if grep -q '^## Directions Index' "$WRITE"; then
    TMP_INIT=$(mktemp)
    awk '
      /^## Directions Index/ {
        print
        print ""
        print "<!-- DIRECTIONS-INDEX:START — generated by scripts/gen-directions-index.sh; do not edit by hand -->"
        print "<!-- DIRECTIONS-INDEX:END -->"
        drop=1; next
      }
      drop && /^---$/  { drop=0; print ""; print; next }   # section ends at a divider…
      drop && /^## /   { drop=0; print ""; print; next }   # …or the next heading
      !drop { print }
    ' "$WRITE" > "$TMP_INIT" && mv "$TMP_INIT" "$WRITE"
    echo "• inserted DIRECTIONS-INDEX markers under the existing heading in $WRITE"
  else
    echo "gen-directions-index.sh: $WRITE has neither the markers nor a '## Directions Index' heading." >&2
    echo "  add these two lines where the table should live, then re-run:" >&2
    echo "    <!-- DIRECTIONS-INDEX:START — generated by scripts/gen-directions-index.sh; do not edit by hand -->" >&2
    echo "    <!-- DIRECTIONS-INDEX:END -->" >&2
    exit 2
  fi
fi
grep -q 'DIRECTIONS-INDEX:END' "$WRITE" || {
  echo "gen-directions-index.sh: $WRITE has a START marker but no matching END marker" >&2
  exit 2
}

TMP_BODY=$(mktemp)
printf '%s\n' "$BODY" > "$TMP_BODY"
TMP_OUT=$(mktemp)
awk -v bodyfile="$TMP_BODY" '
  BEGIN { body=""; while ((getline line < bodyfile) > 0) body = body line "\n" }
  /DIRECTIONS-INDEX:START/ { print; printf "%s", body; skip=1; next }
  /DIRECTIONS-INDEX:END/   { skip=0 }
  !skip { print }
' "$WRITE" > "$TMP_OUT"
mv "$TMP_OUT" "$WRITE"
rm -f "$TMP_BODY"
echo "✓ regenerated Directions Index in $WRITE"
